[package]
name = "types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb="2.3.0"
serde_json="1.0.85"
serde = { version = "1.0", features = ["derive"] }