name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build project
      run: cargo build --release --verbose
    - name: Install sshpass
      run: sudo apt-get install sshpass
    - name: Copy release directory to server
      run: |
        sshpass -p ${{ secrets.VPS_PASSWORD }} scp -o StrictHostKeyChecking=no -r target/release root@${{ secrets.VPS_HOST }}:/home/alpadrive/server/
      env:
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
    - name: Restart systemd process on server
      run: |
        sshpass -p ${{ secrets.VPS_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_HOST }} 'sudo systemctl restart server.service'
      env:
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
