name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.75.0  # specify the Rust version here
        override: true
    - name: build project
      run: cargo build --release --verbose
    - name: install tools
      run: sudo apt-get install sshpass rsync
    - name: write changes to server
      run: |
        sshpass -p ${{ secrets.VPS_PASSWORD }} rsync -avz -e 'ssh -o StrictHostKeyChecking=no' target/release/ root@${{ secrets.VPS_HOST }}:/home/alpadrive/server/release;sshpass -p ${{ secrets.VPS_PASSWORD }} rsync -avz -e 'ssh -o StrictHostKeyChecking=no' html/ root@${{ secrets.VPS_HOST }}:/home/alpadrive/server/html
      env:
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
    - name: restart server
      run: |
        sshpass -p ${{ secrets.VPS_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_HOST }} 'sudo systemctl restart server.service'
      env:
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
